name: general_information
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.3.0
  timeago: ^3.7.0
  toggle_switch: ^2.3.0
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.0

  flutter_test:
    sdk: flutter
flutter:
  # generate: true
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
